name: "example-nightly-wheels"
description: "Upload nightly wheels to Anaconda cloud"
author: "Matthew Feickert"
branding:
  icon: "package"
  color: "green"
inputs:
  python:
    description: "Command to run Python"
    required: true
    default: "python"
  requirements-file:
    description: "Path to a requirements file"
    required: false
    default: "requirements.txt"
  options:
    description: "Extra CLI options"
    required: false
  project-repo:
    description: "GitHub project name to download built wheels from"
    required: true
  token:
    description: "GitHub token for access to gh API"
    required: false
    default: "secrets.GITHUB_TOKEN"
runs:
  using: "composite"
  steps:
    - name: Install micromamba and anaconda-client
      uses: mamba-org/provision-with-micromamba@v12
      with:
        environment-file: false
        environment-name: nightly-wheels
        extra-specs: anaconda-client=1.10.0
        channels: main

    - name: Check anaconda-client
      run: anaconda --help
      shell: bash -l {0}

    # c.f. https://github.com/actions/download-artifact/issues/3#issuecomment-1017141067
    - name: Download wheel artifacts from last build on 'main'
      run: |
        BRANCH="main"
        WORKFLOW_NAME="cibuildwheel.yml"
        ARTIFACT_NAME="wheels"
        gh run --repo "${{ inputs.project-repo }}" \
            list --branch "${BRANCH}" \
                --workflow "${WORKFLOW_NAME}" \
                --json event,status,databaseId > runs.json

        # Filter on 'push' events to main (merged PRs) that have completed
        jq --compact-output \
          '[ .[] | select(.event == "push") | select(.status == "completed") ]' \
          runs.json > pushes.json

        # Get id of latest build of wheels
        RUN_ID=$(
          jq --compact-output \
            'sort_by(.databaseId) | reverse | .[0].databaseId' pushes.json
        )
        gh run --repo "${{ inputs.project-repo }}" \
            download "${RUN_ID}" --name "${ARTIFACT_NAME}"
        mkdir dist
        mv *.whl dist/
        ls -l dist/
      shell: bash

    # - name: Install micromamba and anaconda-client
    # - run: "${{ inputs.python }} -m pip install --no-deps --require-hashes --only-binary :all: ${{ inputs.options }} -r ${{ inputs.requirements-file }}"
    #   shell: bash -l {0}
